// ============================================================
// Rezo Mapou — Fichier de traductions (strings.js)
// Éditez ce fichier pour modifier tous les textes du site
// Langues: ht (Kreyòl), fr (Français), en (English)
// ============================================================

const STRINGS = {
  ht: {
    // Navigation
    nav_home: "Akèy",
    nav_program: "Pwogram",
    nav_sentinelle: "Santinèl",
    nav_coach: "Coach",
    nav_dashboard: "Tablodbò",
    nav_join: "Enskri",

    // Stats bar
    stats_sentinelles: "Santinèl",
    stats_coaches: "Coach",
    stats_loading: "...",

    // Hero
    hero_tag: "Rezo Machann Nasyonal · Ayiti 2026",
    hero_t1: "Ou se",
    hero_t2: "Rezo Mapou.",
    hero_t3: "Vini grandi.",
    hero_lead: "Yon rezo nasyonal ki sipòte machann ak antreprenè nan tout Ayiti — vizibilite, koneksyon, ak sipò konkrè chak mwa.",
    hero_cta_s: "Enskri kòm Santinèl",
    hero_cta_c: "Enskri kòm Coach",
    hero_cta_more: "Kijan sa Travay",

    // Mapou section
    map_eye: "Senbòl Nou",
    map_title: "Poukisa Mapou?",
    map_p1: "Pyebwa Mapou se pyebwa ki pi solid ann Ayiti. Li pa grandi vit — li bati rasin pwofon anvan li leve anlè. Siklòn pa ka rache l paske pa gen yon sèl rasin ki pote tout pwa a.",
    map_p2: "Machann yo se rasin ekonomi Ayisyen an. Chak machann dlo, chak vandè manje, chak ti komèsan — se yon rasin. Ansanm, nou fòme yon rezo ki pa ka rache.",
    map_dis_title: "Yon bagay enpòtan pou nou di klè:",
    map_dis1: "Rezo Mapou pa gen okenn afiliyasyon relijye — ni katolik, ni pwotestan, ni vodou, ni okenn lòt kwayans. Senbòl mapou a se eritaj tout pèp Ayisyen san eksepsyon.",
    map_dis2: "Rezo Mapou pa gen okenn afiliyasyon politik — ni pati, ni kandida, ni gouvènman. Nou travay pou machann ak kominote yo sèlman.",
    map_dis3: "Tout moun — kèlkeswa relijyon oswa politik yo — gen plas nan Rezo Mapou. Sèl kondisyon: vle wè Ayiti avanse.",

    // Programme
    prog_eye: "Pwogram Nou",
    prog_title: "Map Sipote Lakay",
    prog_lead: "3 etap senp. Yon sipò reyèl chak mwa.",
    step1_title: "Enskri — Gratis",
    step1_desc: "Kreye pwofil ou kòm Santinèl. Pa peye anyen. Enskripsyon louvri jiska 1 me.",
    step2_title: "Coach Chwazi Ou",
    step2_desc: "Coach yo gade pwofil ou epi deside sipòte ou. Yo peye frè enskripsyon pwogram nan pou ou.",
    step3_title: "Resevwa Sipò Chak Mwa",
    step3_desc: "Chak mwa ou resevwa sipò — akondisyon ou reyalize 3 aktivite rezo a.",
    cond1_title: "① Poste sou Rezo Mapou",
    cond1_desc: "Pataje yon post sou paj nou pou pale de Coach ou ak aktivite ou.",
    cond2_title: "② Aktivite Kominotè",
    cond2_desc: "Patisipe nan omwen yon aktivite kominotè ki gen valè nan mwa a.",
    cond3_title: "③ Rapò Mansyèl",
    cond3_desc: "Ranpli rapò mansyèl rezo a sou aktivite ou ak zòn ou.",

    // CTA section
    cta_eye: "Apèl Nou",
    cta_quote: "Ou se yon machann dlo, manje, legim — ou se yon Santinèl k ap bay ekonomi an jaret. Vini nan Rezo Mapou.",
    cta_s: "Enskri kòm Santinèl — Gratis",
    cta_c: "Enskri kòm Coach",

    // Forms - common
    f_prenom: "Prenon",
    f_nom: "Non",
    f_email: "Imèl",
    f_phone: "Telefòn",
    f_phone_hint: "Nimewo telefòn ou",
    f_whatsapp: "WhatsApp",
    f_whatsapp_hint: "Si diferan ak telefòn ou",
    f_dept: "Depatman",
    f_dept_ph: "— Chwazi depatman —",
    f_commune: "Komin",
    f_commune_ph: "— Chwazi komin —",
    f_zone: "Zòn / Katye",
    f_zone_hint: "Kote egzakteman ou travay la",
    f_message: "Mesaj (opsyonèl)",
    f_consent: "Mwen aksepte Tèm ak Politik Konfidansyalite Rezo Mapou.",
    f_submit_s: "Enskri kòm Santinèl — Gratis",
    f_submit_c: "Enskri kòm Coach",

    // Sentinelle form
    s_title: "Enskri kòm Santinèl",
    s_sub: "Gratis. Yon minit. Ou ka envite yon Coach pita.",
    s_sec1: "Enfòmasyon Pèsonèl",
    s_sec2: "Kote Ou Ye",
    s_sec3: "Aktivite & Rezo Sosyal",
    s_sec4: "Preferans",
    f_activite: "Tip Aktivite",
    f_activite_hint: "Egz: Machann dlo, boutik, kwafè...",
    f_video: "Lyen Videyo (opsyonèl)",
    f_video_hint: "YouTube oswa TikTok — prezante tèt ou",
    f_payment: "Metòd Peman Prefere",
    f_payment_hint: "Koman ou vle resevwa kado pa w la?",
    pay_moncash: "MonCash",
    pay_natcash: "NatCash",
    pay_cash: "Lajan Cash",
    pay_virement: "Virement Bancaire",
    pay_autre: "Lòt",
    self_note: "💡 Ou vle sipòte tèt ou? Ou ka enskri tou kòm Coach. Sipò mansyèl la pral pi ba — men ou benefisye tout avantaj vizibilite rezo a.",

    // Coach form
    c_title: "Enskri kòm Coach",
    c_sub: "Pwofil ou ap vizib. Ou chwazi ki Santinèl pou sipòte.",
    c_sec1: "Enfòmasyon Pèsonèl",
    c_sec2: "Pwofil Coach",
    c_sec3: "Rezo Sosyal",
    c_sec4: "Motivasyon",
    f_location: "Ou baze kote?",
    loc_haiti: "Ann Ayiti",
    loc_diaspora: "Dyaspora",
    f_org: "Òganizasyon / Antrepriz",
    f_org_hint: "Opsyonèl — si ou reprezante yon enstitisyon",
    f_logo: "Lyen Logo / Foto Pwofil",
    f_logo_hint: "Opsyonèl — Facebook, Google Drive...",
    f_website: "Site Web",
    f_website_hint: "Opsyonèl",
    f_message_c: "Poukisa ou vle vin Coach?",
    f_message_c_hint: "Opsyonèl — di nou motivasyon ou",

    // Success messages
    suc_s_title: "Mèsi — ou nan rezo a!",
    suc_s_msg: "Nou pral kontakte ou byento. Rasin fò, pyebwa leve.",
    suc_s_share: "Pataje lyen enskripsyon an sou rezo sosyal ou. Si ou konn yon Coach, envitel enskri.",
    suc_c_title: "Mèsi Coach — bienveni!",
    suc_c_msg: "Pwofil ou pral vizib sou sit la. Nou pral kontakte ou pou etap yo.",

    // Footer
    foot_tagline: "Rezo Machann Nasyonal · Ayiti",
    foot_motto: "Rasin fò, pyebwa leve.",
    foot_nav: "Navigasyon",
    foot_legal: "Legal",
    lnk_privacy: "Konfidansyalite",
    lnk_terms: "Tèm",
    lnk_copyright: "Dwa Otè",

    // Dashboard
    dash_title: "Tablodbò Rezo Mapou",
    dash_sub: "Enskripsyon an tan reyèl",
    dash_sentinelles: "Santinèl Enskri",
    dash_coaches: "Coach Aktif",
    dash_depts: "Depatman",
    dash_communes: "Komin",
    dash_by_dept: "Pa Depatman",
    dash_by_commune: "Pa Komin (Top 10)",
    dash_refresh: "Aktyalize",
    dash_loading: "Ap chaje done...",
    dash_empty: "Pa gen done pou kounye a.",
    dash_error: "Erè koneksyon.",
  },

  fr: {
    nav_home: "Accueil",
    nav_program: "Programme",
    nav_sentinelle: "Sentinelle",
    nav_coach: "Coach",
    nav_dashboard: "Tableau de bord",
    nav_join: "S'inscrire",
    stats_sentinelles: "Sentinelles",
    stats_coaches: "Coachs",
    stats_loading: "...",
    hero_tag: "Réseau Marchand National · Haïti 2026",
    hero_t1: "Vous êtes",
    hero_t2: "Rezo Mapou.",
    hero_t3: "Venez grandir.",
    hero_lead: "Un réseau national qui soutient les marchands et entrepreneurs à travers Haïti — visibilité, connexions et soutien concret chaque mois.",
    hero_cta_s: "S'inscrire comme Sentinelle",
    hero_cta_c: "S'inscrire comme Coach",
    hero_cta_more: "Comment ça marche",
    map_eye: "Notre Symbole",
    map_title: "Pourquoi Mapou?",
    map_p1: "L'arbre Mapou est l'arbre le plus solide d'Haïti. Il ne grandit pas vite — il construit des racines profondes avant de s'élever. Les cyclones ne peuvent pas le déraciner.",
    map_p2: "Les marchands sont les racines de l'économie haïtienne. Chaque marchand d'eau, chaque vendeur de nourriture — est une racine. Ensemble, nous formons un réseau impossible à déraciner.",
    map_dis_title: "Une chose importante à dire clairement :",
    map_dis1: "Rezo Mapou n'a aucune affiliation religieuse — ni catholique, ni protestante, ni vaudou. Le symbole du mapou est le patrimoine de tout le peuple haïtien.",
    map_dis2: "Rezo Mapou n'a aucune affiliation politique — ni parti, ni candidat, ni gouvernement. Nous travaillons pour les marchands et les communautés.",
    map_dis3: "Toute personne — quelle que soit sa religion ou politique — a sa place dans Rezo Mapou. Une seule condition : vouloir voir Haïti avancer.",
    prog_eye: "Notre Programme",
    prog_title: "Map Sipote Lakay",
    prog_lead: "3 étapes simples. Un soutien réel chaque mois.",
    step1_title: "S'inscrire — Gratuit",
    step1_desc: "Créez votre profil Sentinelle. Gratuit. Inscriptions ouvertes jusqu'au 1er mai.",
    step2_title: "Un Coach vous choisit",
    step2_desc: "Les Coachs consultent votre profil et peuvent décider de vous soutenir en payant les frais d'inscription.",
    step3_title: "Recevez un soutien mensuel",
    step3_desc: "Chaque mois vous recevez un soutien — à condition de réaliser 3 activités du réseau.",
    cond1_title: "① Poster sur Rezo Mapou",
    cond1_desc: "Partager un post sur notre page pour parler de votre Coach et de vos activités.",
    cond2_title: "② Activité Communautaire",
    cond2_desc: "Participer à au moins une activité communautaire significative dans le mois.",
    cond3_title: "③ Rapport Mensuel",
    cond3_desc: "Remplir le rapport mensuel du réseau sur vos activités et votre zone.",
    cta_eye: "Notre Appel",
    cta_quote: "Que vous vendiez de l'eau, de la nourriture ou des légumes — vous soutenez l'économie. Rejoignez Rezo Mapou.",
    cta_s: "S'inscrire comme Sentinelle — Gratuit",
    cta_c: "S'inscrire comme Coach",
    f_prenom: "Prénom", f_nom: "Nom", f_email: "Email",
    f_phone: "Téléphone", f_phone_hint: "Votre numéro de téléphone",
    f_whatsapp: "WhatsApp", f_whatsapp_hint: "Si différent de votre téléphone",
    f_dept: "Département", f_dept_ph: "— Choisir un département —",
    f_commune: "Commune", f_commune_ph: "— Choisir une commune —",
    f_zone: "Zone / Quartier", f_zone_hint: "Où exactement vous travaillez",
    f_message: "Message (optionnel)",
    f_consent: "J'accepte les Conditions et la Politique de Confidentialité de Rezo Mapou.",
    f_submit_s: "S'inscrire comme Sentinelle — Gratuit",
    f_submit_c: "S'inscrire comme Coach",
    s_title: "S'inscrire comme Sentinelle",
    s_sub: "Gratuit. Une minute. Vous pourrez inviter un Coach plus tard.",
    s_sec1: "Informations Personnelles", s_sec2: "Localisation",
    s_sec3: "Activité & Réseaux Sociaux", s_sec4: "Préférences",
    f_activite: "Type d'activité", f_activite_hint: "Ex: Marchand d'eau, boutique, coiffeur...",
    f_video: "Lien vidéo (optionnel)", f_video_hint: "YouTube ou TikTok — présentez-vous",
    f_payment: "Méthode de paiement préférée",
    f_payment_hint: "Comment voulez-vous recevoir votre soutien mensuel ?",
    pay_moncash: "MonCash", pay_natcash: "NatCash", pay_cash: "Espèces",
    pay_virement: "Virement Bancaire", pay_autre: "Autre",
    self_note: "💡 Vous voulez vous auto-soutenir ? Inscrivez-vous aussi comme Coach. Le soutien mensuel sera moindre, mais vous bénéficiez de toute la visibilité du réseau.",
    c_title: "S'inscrire comme Coach",
    c_sub: "Votre profil sera visible. Vous choisissez quelle Sentinelle soutenir.",
    c_sec1: "Informations Personnelles", c_sec2: "Profil Coach",
    c_sec3: "Réseaux Sociaux", c_sec4: "Motivation",
    f_location: "Vous êtes basé où ?",
    loc_haiti: "En Haïti", loc_diaspora: "Diaspora",
    f_org: "Organisation / Entreprise", f_org_hint: "Optionnel — si vous représentez une institution",
    f_logo: "Lien Logo / Photo de profil", f_logo_hint: "Optionnel — Facebook, Google Drive...",
    f_website: "Site Web", f_website_hint: "Optionnel",
    f_message_c: "Pourquoi voulez-vous être Coach ?", f_message_c_hint: "Optionnel — dites-nous votre motivation",
    suc_s_title: "Merci — vous êtes dans le réseau !",
    suc_s_msg: "Nous vous contacterons bientôt. Rasin fò, pyebwa leve.",
    suc_s_share: "Partagez le lien sur vos réseaux. Si vous connaissez un Coach potentiel, invitez-le à s'inscrire.",
    suc_c_title: "Merci Coach — bienvenu !",
    suc_c_msg: "Votre profil sera visible sur le site. Nous vous contacterons pour les prochaines étapes.",
    foot_tagline: "Réseau Marchand National · Haïti",
    foot_motto: "Rasin fò, pyebwa leve.",
    foot_nav: "Navigation", foot_legal: "Légal",
    lnk_privacy: "Confidentialité", lnk_terms: "Conditions", lnk_copyright: "Droits d'auteur",
    dash_title: "Tableau de Bord Rezo Mapou",
    dash_sub: "Inscriptions en temps réel",
    dash_sentinelles: "Sentinelles Inscrites", dash_coaches: "Coachs Actifs",
    dash_depts: "Départements", dash_communes: "Communes",
    dash_by_dept: "Par Département", dash_by_commune: "Par Commune (Top 10)",
    dash_refresh: "Actualiser", dash_loading: "Chargement...",
    dash_empty: "Pas de données pour le moment.", dash_error: "Erreur de connexion.",
  },

  en: {
    nav_home: "Home", nav_program: "Program", nav_sentinelle: "Sentinel",
    nav_coach: "Coach", nav_dashboard: "Dashboard", nav_join: "Register",
    stats_sentinelles: "Sentinels", stats_coaches: "Coaches", stats_loading: "...",
    hero_tag: "National Merchant Network · Haiti 2026",
    hero_t1: "You are", hero_t2: "Rezo Mapou.", hero_t3: "Come grow.",
    hero_lead: "A national network supporting merchants and entrepreneurs across Haiti — visibility, connections, and concrete monthly support.",
    hero_cta_s: "Register as Sentinel", hero_cta_c: "Register as Coach", hero_cta_more: "How It Works",
    map_eye: "Our Symbol", map_title: "Why Mapou?",
    map_p1: "The Mapou tree is Haiti's most resilient tree. It doesn't grow fast — it builds deep roots before rising. Hurricanes cannot uproot it.",
    map_p2: "Merchants are the roots of the Haitian economy. Every water vendor, every food seller — is a root. Together, we form a network that cannot be uprooted.",
    map_dis_title: "One thing important to state clearly:",
    map_dis1: "Rezo Mapou has no religious affiliation — neither Catholic, Protestant, Vodou, nor any other belief. The mapou symbol belongs to all Haitian people.",
    map_dis2: "Rezo Mapou has no political affiliation — no party, no candidate, no government. We work for merchants and communities only.",
    map_dis3: "Anyone — regardless of religion or politics — has a place in Rezo Mapou. One condition: wanting Haiti to move forward.",
    prog_eye: "Our Program", prog_title: "Map Sipote Lakay", prog_lead: "3 simple steps. Real support every month.",
    step1_title: "Register — Free", step1_desc: "Create your Sentinel profile. Free. Open until May 1st.",
    step2_title: "A Coach Chooses You", step2_desc: "Coaches browse profiles and can decide to support you by paying your enrollment fee.",
    step3_title: "Receive Monthly Support", step3_desc: "Each month you receive support — provided you complete 3 network activities.",
    cond1_title: "① Post on Rezo Mapou", cond1_desc: "Share a post on our page about your Coach and activities.",
    cond2_title: "② Community Activity", cond2_desc: "Participate in at least one meaningful community activity per month.",
    cond3_title: "③ Monthly Report", cond3_desc: "Complete the monthly network report on your activities and area.",
    cta_eye: "Our Call",
    cta_quote: "Whether you sell water, food, or vegetables — you hold up the economy. Join Rezo Mapou.",
    cta_s: "Register as Sentinel — Free", cta_c: "Register as Coach",
    f_prenom: "First Name", f_nom: "Last Name", f_email: "Email",
    f_phone: "Phone", f_phone_hint: "Your phone number",
    f_whatsapp: "WhatsApp", f_whatsapp_hint: "If different from your phone",
    f_dept: "Department", f_dept_ph: "— Choose a department —",
    f_commune: "Commune", f_commune_ph: "— Choose a commune —",
    f_zone: "Zone / Neighborhood", f_zone_hint: "Where exactly you work",
    f_message: "Message (optional)",
    f_consent: "I accept Rezo Mapou's Terms and Privacy Policy.",
    f_submit_s: "Register as Sentinel — Free", f_submit_c: "Register as Coach",
    s_title: "Register as a Sentinel", s_sub: "Free. One minute. You can invite a Coach later.",
    s_sec1: "Personal Information", s_sec2: "Location",
    s_sec3: "Activity & Social Media", s_sec4: "Preferences",
    f_activite: "Activity type", f_activite_hint: "E.g.: Water vendor, shop, hairdresser...",
    f_video: "Video link (optional)", f_video_hint: "YouTube or TikTok — introduce yourself",
    f_payment: "Preferred payment method", f_payment_hint: "How do you want to receive your monthly support?",
    pay_moncash: "MonCash", pay_natcash: "NatCash", pay_cash: "Cash",
    pay_virement: "Bank Transfer", pay_autre: "Other",
    self_note: "💡 Want to self-support? Register as a Coach for your own profile. Monthly support will be less, but you get full network visibility.",
    c_title: "Register as a Coach", c_sub: "Your profile will be visible. You choose which Sentinel to support.",
    c_sec1: "Personal Information", c_sec2: "Coach Profile",
    c_sec3: "Social Media", c_sec4: "Motivation",
    f_location: "Where are you based?", loc_haiti: "In Haiti", loc_diaspora: "Diaspora",
    f_org: "Organization / Business", f_org_hint: "Optional — if you represent an institution",
    f_logo: "Logo / Profile photo link", f_logo_hint: "Optional — Facebook, Google Drive...",
    f_website: "Website", f_website_hint: "Optional",
    f_message_c: "Why do you want to be a Coach?", f_message_c_hint: "Optional — tell us your motivation",
    suc_s_title: "Thank you — you're in the network!",
    suc_s_msg: "We'll be in touch soon. Rasin fò, pyebwa leve.",
    suc_s_share: "Share the registration link on your social media. If you know a potential Coach, invite them.",
    suc_c_title: "Thank you Coach — welcome!",
    suc_c_msg: "Your profile will be visible on the site. We'll contact you for next steps.",
    foot_tagline: "National Merchant Network · Haiti",
    foot_motto: "Rasin fò, pyebwa leve.",
    foot_nav: "Navigation", foot_legal: "Legal",
    lnk_privacy: "Privacy", lnk_terms: "Terms", lnk_copyright: "Copyright",
    dash_title: "Rezo Mapou Dashboard",
    dash_sub: "Real-time registrations",
    dash_sentinelles: "Registered Sentinels", dash_coaches: "Active Coaches",
    dash_depts: "Departments", dash_communes: "Communes",
    dash_by_dept: "By Department", dash_by_commune: "By Commune (Top 10)",
    dash_refresh: "Refresh", dash_loading: "Loading...",
    dash_empty: "No data yet.", dash_error: "Connection error.",
  }
};

// Département codes (4 chars)
const DEPT_CODES = {
  "Artibonite": "ARTB", "Centre": "CNTR", "Grand'Anse": "GDAS",
  "Nippes": "NIPP", "Nord": "NORD", "Nord-Est": "NRDE",
  "Nord-Ouest": "NRDO", "Ouest": "OUES", "Sud": "SUDD", "Sud-Est": "SDST"
};

// Commune codes (4 chars) — first 4 unique chars of commune name
const COMMUNE_CODES = {
  "Dessalines":"DSSL","Desdunes":"DSDN","Ennery":"ENNR","Gros-Morne":"GRSM",
  "La Chapelle":"LCHP","Marchand Dessalines":"MRDS","Marmelade":"MRML",
  "Saint-Marc":"STMR","Saint-Michel de l'Atalaye":"STMI","Saint-Raphaël":"STRP",
  "Verrettes":"VRRT","Belladère":"BLLR","Boucan Carré":"BCCR","Hinche":"HNCH",
  "Lascahobas":"LSCB","Mirebalais":"MRBL","Savanette":"SVNT","Thomonde":"THMD",
  "Abricots":"ABRC","Anse-d'Ainault":"ASAN","Beaumont":"BMON","Bonbon":"BNBN",
  "Chambellan":"CHBL","Dame-Marie":"DMRY","Jérémie":"JRMI","Latibolière":"LTBL",
  "Les Irois":"LSIR","Moron":"MRON","Roseaux":"ROSW","Tiburon":"TBRN",
  "Arnaud":"ARND","Anse-à-Veau":"ANSV","Barradères":"BRDR","Fond des Nègres":"FNDN",
  "Jérôme":"JROM","L'Asile":"LASL","Miragoane":"MRGN","Paillant":"PLNT",
  "Plaisance du Sud":"PLSD","Petit-Trou-de-Nippes":"PTTN","Acul du Nord":"ACLN",
  "Bahon":"BAHN","Borgne":"BRGN","Cap-Haïtien":"CPHT","Dondon":"DNDN",
  "Grande Rivière du Nord":"GRDN","Limonade":"LMND","Milot":"MLOT","Pignon":"PGNN",
  "Pilate":"PLAT","Plaisance":"PLSN","Ranquitte":"RNQT","Sainte-Suzanne":"STSZ",
  "Trou-du-Nord":"TRDN","Caracol":"CRCL","Carice":"CRCE","Ferrier":"FERR",
  "Fort-Liberté":"FTLB","Mombin Crochu":"MMCR","Mont-Organisé":"MNTO",
  "Ouanaminthe":"WNMT","Perches":"PRCH","Terrier Rouge":"TRRG","Vallières":"VLLR",
  "Wanament":"WNMN","Anse-à-Foleur":"ANSF","Baie de Henne":"BDHN",
  "Bassin Bleu":"BSNB","Bombardopolis":"BMBP","Chansolme":"CHNS","Jean Rabel":"JNRB",
  "La Tortue":"LTRТ","Môle Saint-Nicolas":"MLSN","Port-de-Paix":"PTDP",
  "Saint-Louis du Nord":"SLND","Terre Neuve":"TRNV","Arcahaie":"ARCH",
  "Cabaret":"CBRT","Carrefour":"CRFR","Cité Soleil":"CTSL","Cornillon":"CRNL",
  "Croix des Bouquets":"CRBQ","Delmas":"DLMS","Gressier":"GRSS","Ganthier":"GNTH",
  "Kenscoff":"KNSC","La Gonâve":"LGNV","Léogâne":"LOGN","Pétion-Ville":"PTVL",
  "Port-au-Prince":"PTPR","Tabarre":"TBRR","Thomazeau":"THMZ","Titanyen":"TTYN",
  "Aquin":"AQIN","Arniquet":"ARNQ","Camp Perrin":"CMPR","Cavaillon":"CVLN",
  "Chantal":"CHNT","Côtes de Fer":"CTDF","Les Cayes":"LSCY","Maniche":"MNCH",
  "Port-à-Piment":"PTPM","Port-Salut":"PTSL","Saint-Jean du Sud":"SJDS",
  "Saint-Louis du Sud":"SLSD","Torbeck":"TRBK","Bainet":"BNET","Belle Anse":"BLNS",
  "Cayes-Jacmel":"CYJM","Grand Gosier":"GRGS","Jacmel":"JCML","La Vallée":"LVLL",
  "Marigot":"MRGT","Thiotte":"THTT"
};

// Haiti departments + communes
const HAITI = {
  "Artibonite":["Dessalines","Desdunes","Ennery","Gros-Morne","La Chapelle","Marchand Dessalines","Marmelade","Saint-Marc","Saint-Michel de l'Atalaye","Saint-Raphaël","Verrettes"],
  "Centre":["Belladère","Boucan Carré","Hinche","Lascahobas","Mirebalais","Savanette","Thomonde"],
  "Grand'Anse":["Abricots","Anse-d'Ainault","Beaumont","Bonbon","Chambellan","Dame-Marie","Jérémie","Latibolière","Les Irois","Moron","Roseaux","Tiburon"],
  "Nippes":["Arnaud","Anse-à-Veau","Barradères","Fond des Nègres","Jérôme","L'Asile","Miragoane","Paillant","Plaisance du Sud","Petit-Trou-de-Nippes"],
  "Nord":["Acul du Nord","Bahon","Borgne","Cap-Haïtien","Dondon","Grande Rivière du Nord","Limonade","Milot","Pignon","Pilate","Plaisance","Ranquitte","Sainte-Suzanne","Trou-du-Nord"],
  "Nord-Est":["Caracol","Carice","Ferrier","Fort-Liberté","Mombin Crochu","Mont-Organisé","Ouanaminthe","Perches","Terrier Rouge","Vallières","Wanament"],
  "Nord-Ouest":["Anse-à-Foleur","Baie de Henne","Bassin Bleu","Bombardopolis","Chansolme","Jean Rabel","La Tortue","Môle Saint-Nicolas","Port-de-Paix","Saint-Louis du Nord","Terre Neuve"],
  "Ouest":["Arcahaie","Cabaret","Carrefour","Cité Soleil","Cornillon","Croix des Bouquets","Delmas","Gressier","Ganthier","Kenscoff","La Gonâve","Léogâne","Pétion-Ville","Port-au-Prince","Tabarre","Thomazeau","Titanyen"],
  "Sud":["Aquin","Arniquet","Camp Perrin","Cavaillon","Chantal","Côtes de Fer","Les Cayes","Maniche","Port-à-Piment","Port-Salut","Saint-Jean du Sud","Saint-Louis du Sud","Torbeck"],
  "Sud-Est":["Bainet","Belle Anse","Cayes-Jacmel","Grand Gosier","Jacmel","La Vallée","Marigot","Thiotte"]
};

const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbzzZ-7lHjzYLPAaGCSPQKZXMivufv6TnCVERc0P8CtM1n2kWl9iR4GL8JUD4Tw10dB8/exec';

// ============================================================
// CONFIG — Edit here to change backend settings
// ============================================================
const SHEET_ID = '15gOrMlb7tPEaOVjCNSk1Co625OXYMo9QS9OnYVbSLc0';

// ============================================================
// FAKE DATA POOLS — used by seeddata and dashboard auto-seed
// ============================================================
const FAKE_FIRSTNAMES = ["Marie","Jean","Roseline","Claude","Nadège","Frantz","Sophia","Patrick","Kettely","Dieuseul","Yanick","Farah","Luckson","Mireille","Edwige","Roberson","Guerda","Widler","Junie","Kervens","Marlène","Samson","Yvelise","Joël","Carline","Renald","Gisèle","Hervé","Lunise","Dieudonne"];
const FAKE_LASTNAMES = ["Desroches","Baptiste","Pierre","Mentor","Joseph","Celestin","Duval","Lamarre","François","Blanc","Charles","Estimé","Dorismond","Augustin","Prophète","Casimir","Sainvil","Thermidor","Beaubrun","Toussaint","Lubin","Dorsainvil","Noël","Hyppolite","Lafortune","Morisseau","Belizaire","Volcy","Cadet","Dorcé"];
const FAKE_ACTIVITIES = ["Machann dlo","Machann manje","Machann legim","Boutik","Machann frèt","Kwafè","Mekanisyen","Machann rad","Epicerie","Machann poul","Machann chabon","Boulanje","Machann fritay","Machann ji","Tèlkominikasyon"];
const FAKE_COACH_ORGS = ["","","","Diaspora Haiti","Association Ayisyen","","","Haiti Forward","","Haitian Business Network","","",""];

// Commune population weights for realistic distribution
const COMMUNE_WEIGHTS = {
  "Port-au-Prince":22,"Delmas":14,"Carrefour":11,"Pétion-Ville":9,"Cité Soleil":8,
  "Cap-Haïtien":10,"Saint-Marc":6,"Les Cayes":6,"Gonaïves":7,"Hinche":4,
  "Jacmel":5,"Jérémie":4,"Ouanaminthe":4,"Croix des Bouquets":6,"Léogâne":4,
  "Arcahaie":3,"Tabarre":5,"Mirebalais":3
};
