const LangService = {
    currentLang: (localStorage.getItem('rmn_lang') || 'ht'),
    dictionary: {
        ht: {
            lang_ht: 'Kreyol', lang_fr: 'Francais', lang_en: 'English',
            nav_home: 'Akèy', nav_about: 'Filozofi', nav_program: 'Pwogram', nav_register: 'Enskri', nav_contact: 'Kontakte nou',
            footer_copyright: 'Dwa Otè', footer_privacy: 'Konfidansyalite',
            footer_terms: 'Tèm Itilizasyon', footer_meta: '© 2026 Rezo Mapou Nasyonal',
            tab_filozofi: 'Filozofi', tab_program: 'Pwogram',
            hero_tag: 'Rezo Machann Nasyonal - Ayiti 2026',
            hero_h1a: 'Ou se', hero_h1b: 'Rezo Mapou.', hero_h1c: 'Vini grandi.',
            hero_lead: 'Yon rezo nasyonal ki sipote machann ak antreprene nan tout Ayiti.',
            hero_cta1: 'Enskri Kounye a - Gratis', hero_cta2: 'Kijan sa Travay',
            map_eye: 'Senbòl Nou', map_title: 'Poukisa Mapou?',
            map_p1: 'Pyebwa Mapou se pyebwa ki pi solid ann Ayiti. Li pa grandi vit - li bati rasin pwofon, long, solid anvan li leve anle.',
            map_p2: 'Se menm lojik la nou itilize pou rezo sa a. Machann yo se rasin ekonomi Ayisyen an. Ansanm, nou fome yon rezo ki pa ka rache.',
            map_dis_title: 'Yon bagay enpòtan pou nou di kle:',
            map_dis1: 'Rezo Mapou pa gen okenn afiliyasyon relijye - ni katolik, ni pwotestan, ni vodou.',
            map_dis2: 'Rezo Mapou pa gen okenn afiliyasyon politik - ni pati, ni kandida, ni gouvènman.',
            map_dis3: 'Tout moun gen plas yo nan Rezo Mapou. Sel kondisyon: vle we Ayiti avanse.',
            prog_eye: 'Pwogram Map Sipote Lakay', prog_title: 'Etap yo, kle kle.',
            ven_call: 'Ou se yon machann - ou se yon Santinel k ap bay ekonomi an jaret.',
            st1t: 'Enskri - Gratis', st1d: 'Enskripsyon louvri depi jodi a. Pa peye anyen.',
            st2t: 'Coach Chwazi Ou', st2d: 'Coach yo gade pwofil Santinel yo epi yo ka deside sipote ou.',
            st3t: 'Resevwa Sipo Chak Mwa', st3d: 'Chak mwa, ou resevwa yon pati nan sipo Coach la peye a.',
            c1t: 'Poste sou Rezo Mapou', c1d: 'Pataje yon post sou paj Rezo Mapou.',
            c2t: 'Aktivite Kominotè', c2d: 'Patisipe nan omwen yon aktivite kominotè nan mwa a.',
            c3t: 'Rapò Mansyel', c3d: 'Ranpli rapo mansyel rezo a.',
                        reg_title: 'Vin yon Rasin Mapou',
            reg_subtitle: 'Gratis. Yon minit. Enskri kounye a.',
            f_sect_identity: 'Idantite',
            f_firstname: 'Prenon', f_lastname: 'Siyati',
            reg_gender: 'Sèks', gender_f: 'Fanm', gender_m: 'Gason', gender_x: 'Lòt',
            f_lang: 'Lang prefere',
            f_email: 'Imèl', f_phone: 'Telefòn',
            f_sect_location: 'Kote ou ye',
            f_country: 'Peyi', f_dept: 'Depatman', f_commune: 'Komin',
            f_city: 'Vil', f_state: 'Eta / Pwovens',
            f_terms_consent: 'Mwen aksepte Tèm ak Politik Konfidansyalite Rezo Mapou.',
            f_submit: 'Enskri kounye a', f_submitting: 'Ap voye...',
            f_success: 'Enskripsyon fèt! Nou pral kontakte ou byento.',
            f_error: 'Yon erè te fèt. Tanpri eseye ankò.',
            f_email_exists: 'Imèl sa a deja enskri.',
            f_phone_exists: 'Nimewo sa a deja enskri.',
            f_email_ok: 'Imèl disponib.', f_phone_ok: 'Nimewo disponib.',
            f_checking: 'Ap verifye...',
            f_sect_payment: 'Peman (opsyonèl)',
            f_payment_hint: 'Nimewo kont pou resevwa peman',
            pay_moncash: 'MonCash', pay_natcash: 'NatCash', pay_none: 'Pa gen kont',
            f_sect_social: 'Rezo Sosyal (opsyonèl)'
            f_website: 'Sit web', f_success_title: 'Mèsi — ou nan rezo a!', f_whatsapp_exists: 'WhatsApp sa a deja enskri.', f_whatsapp_ok: 'WhatsApp disponib.',,
            doc_terms_title: 'Tèm Itilizasyon', doc_terms_meta: 'Avril 2026 · Rezo Mapou Nasyonal',
            doc_terms_h1: '1. Akseptasyon Tèm yo', doc_terms_p1: 'Lè ou itilize sit Rezo Mapou oswa enskri kòm manm, ou aksepte tèm sa yo.',
            doc_terms_h2: '2. Objektif Rezo a', doc_terms_p2: 'Rezo Mapou se yon enfrastrikti sivil ayisyen. Apolitik ak areliijye.',
            doc_terms_h3: '3. Enskripsyon', doc_terms_p3: 'Enfòmasyon ou bay yo egzak, ou gen plis pase 16 an, pa pral itilize rezo a pou aktivite ilegal.',
            doc_terms_h4: '4. Telefòn kòm Idantifyan', doc_terms_p4: 'Nimewo telefòn ou sèvi kòm idantifyan inik. Ou pa ka chanje li ou menm.',
            doc_terms_h5: '5. Konduit Manm', doc_terms_p5: 'Respekte lòt manm, pa difize dezenfòmasyon, pa itilize logo RMN san otorizasyon.',
            doc_terms_h6: '6. Limit Responsabilite', doc_terms_p6: 'RMN pa responsab pou dommaj ki soti nan itilizasyon sit sa a.',
            doc_terms_h7: '7. Chanjman Tèm', doc_terms_p7: 'Nou rezève dwa pou modifye tèm sa yo. Chanjman yo pral pibliye sou sit la.',
            doc_terms_h8: '8. Kontakte nou', doc_terms_p8: 'Email: info@fatraselo.net · WhatsApp: +509 4733 4565',
            doc_privacy_title: 'Politik Konfidansyalite', doc_privacy_meta: 'Avril 2026 · Rezo Mapou Nasyonal',
            doc_privacy_h1: '1. Ki enfòmasyon nou kolekte', doc_privacy_p1: 'Non, imèl, telefòn, depatman, komin ak metòd peman.',
            doc_privacy_h2: '2. Poukisa', doc_privacy_p2: 'Kontakte ou sou aktivite rezo a ak bati yon kat jeyografik patisipan.',
            doc_privacy_h3: '3. Pwoteksyon', doc_privacy_p3: 'Google Sheets pwoteje pa Google Security. Sèlman ekip fondatè ki gen akè.',
            doc_privacy_h4: '4. Konsèvasyon', doc_privacy_p4: 'Pandan rezo a aktif. Voye imèl bay info@fatraselo.net pou efase done ou.',
            doc_privacy_h5: '5. Dwa ou yo', doc_privacy_p5: 'Mande kopi, koreksyon, oswa efasman done ou nenpòt ki lè.',
            doc_privacy_h6: '6. Koulè', doc_privacy_p6: 'Sit sa a pa itilize koulè pou trake ou.',
            doc_privacy_h7: '7. Kontakte nou', doc_privacy_p7: 'Email: info@fatraselo.net · WhatsApp: +509 4733 4565',
            doc_copyright_title: 'Dwa Otè', doc_copyright_meta: '© 2026 Rezo Mapou Nasyonal',
            doc_copyright_h1: '1. Pwopriyete', doc_copyright_p1: 'Tout kontni sou fatraselo.net se pwopriyete eksklizif RMN.',
            doc_copyright_h2: '2. Logo ak Mak', doc_copyright_p2: 'Logo FSL ak RMN se mak enrejistre. Itilizasyon san otorizasyon entèdi.',
            doc_copyright_h3: '3. Entèdiksyon', doc_copyright_p3: 'Pa kopye, repwodwi, ni itilize logo RMN san pèmisyon ekri.',
            doc_copyright_h4: '4. Itilizasyon Otorize', doc_copyright_p4: 'Pataje lyen sit la ak referans klè a sous la.',
            doc_copyright_h5: '5. Kontni Itilizatè', doc_copyright_p5: 'Si ou voye kontni bay RMN, ou ban nou lisans pou itilize li.',
            doc_copyright_h6: '6. Kontakte nou', doc_copyright_p6: 'Email: info@fatraselo.net',
            contact_form_title: 'Voye yon mesaj',
            contact_subject: 'Sijè',
            contact_subject_ph: '— Chwazi sijè —',
            contact_message: 'Mesaj ou',
            contact_send: 'Voye mesaj',
            contact_subj_general: 'Enfòmasyon jeneral',
            contact_subj_complaints: 'Plent',
            contact_subj_suggestions: 'Sijesyon',
            contact_subj_partnership: 'Patènariat'
        },
        fr: {
            lang_ht: 'Kreyol', lang_fr: 'Francais', lang_en: 'English',
            nav_home: 'Accueil', nav_about: 'Philosophie', nav_program: 'Programme', nav_register: 'S\'inscrire', nav_contact: 'Contact',
            footer_legal: 'Mentions legales', footer_privacy: 'Confidentialite',
            footer_terms: 'Conditions', footer_meta: '© 2026 RMNE | Initiative Fatra se Lo',
            tab_filozofi: 'Philosophie', tab_program: 'Programme',
            hero_tag: 'Reseau Marchand National - Haiti 2026',
            hero_h1a: 'Vous etes', hero_h1b: 'Rezo Mapou.', hero_h1c: 'Venez grandir.',
            hero_lead: 'Un reseau national qui soutient les marchands et entrepreneurs a travers Haiti.',
            hero_cta1: 'Inscrire - Gratuit', hero_cta2: 'Comment ca marche',
            map_eye: 'Notre Symbole', map_title: 'Pourquoi Mapou?',
            map_p1: "L'arbre Mapou est l'arbre le plus solide d'Haiti. Il ne grandit pas vite.",
            map_p2: "C'est la meme logique que nous utilisons pour ce reseau.",
            map_dis_title: 'Une chose importante a dire clairement:',
            map_dis1: "Rezo Mapou n'a aucune affiliation religieuse.",
            map_dis2: "Rezo Mapou n'a aucune affiliation politique.",
            map_dis3: "Toute personne a sa place dans Rezo Mapou.",
            prog_eye: 'Programme Map Sipote Lakay', prog_title: 'Les etapes, clairement.',
            ven_call: "Vous soutenez l'economie. Rejoignez Rezo Mapou.",
            st1t: 'Inscrire - Gratuit', st1d: "Les inscriptions sont ouvertes. Gratuit.",
            st2t: 'Un Coach vous choisit', st2d: 'Les Coachs consultent les profils.',
            st3t: 'Recevez un soutien mensuel', st3d: 'Chaque mois, vous recevez une partie du soutien.',
            c1t: 'Poster sur Rezo Mapou', c1d: 'Partager un post sur la page Rezo Mapou.',
            c2t: 'Activite Communautaire', c2d: 'Participer a une activite communautaire.',
            c3t: 'Rapport Mensuel', c3d: 'Remplir le rapport mensuel du reseau.',
                        reg_title: 'Devenez une Racine Mapou',
            reg_subtitle: 'Gratuit. Une minute. Inscrivez-vous maintenant.',
            f_sect_identity: 'Identité',
            f_firstname: 'Prénom', f_lastname: 'Nom de famille',
            reg_gender: 'Genre', gender_f: 'Femme', gender_m: 'Homme', gender_x: 'Autre',
            f_lang: 'Langue préférée',
            f_email: 'Email', f_phone: 'Téléphone',
            f_sect_location: 'Localisation',
            f_country: 'Pays', f_dept: 'Département', f_commune: 'Commune',
            f_city: 'Ville', f_state: 'État / Province',
            f_terms_consent: "J'accepte les Conditions et la Politique de Confidentialité.",
            f_submit: "S'inscrire maintenant", f_submitting: 'Envoi en cours...',
            f_success: 'Inscription réussie! Nous vous contacterons bientôt.',
            f_error: 'Une erreur est survenue. Veuillez réessayer.',
            f_email_exists: 'Cet email est déjà enregistré.',
            f_phone_exists: 'Ce numéro est déjà enregistré.',
            f_email_ok: 'Email disponible.', f_phone_ok: 'Numéro disponible.',
            f_checking: 'Vérification...',
            f_sect_payment: 'Paiement (optionnel)',
            f_payment_hint: 'Numéro de compte pour recevoir les paiements',
            pay_moncash: 'MonCash', pay_natcash: 'NatCash', pay_none: 'Pas de compte',
            f_sect_social: 'Réseaux Sociaux (optionnel)'
            f_website: 'Site web', f_success_title: 'Merci — vous êtes dans le réseau!', f_whatsapp_exists: 'Ce WhatsApp est déjà enregistré.', f_whatsapp_ok: 'WhatsApp disponible.',,
            doc_terms_title: "Conditions d'Utilisation", doc_terms_meta: 'Avril 2026 · Rezo Mapou Nasyonal',
            doc_terms_h1: '1. Acceptation', doc_terms_p1: "En utilisant le site ou vous inscrivant comme membre, vous acceptez ces conditions.",
            doc_terms_h2: '2. Objectif', doc_terms_p2: "Réseau civil haïtien apolitique et areligieux.",
            doc_terms_h3: '3. Inscription', doc_terms_p3: "Informations exactes, plus de 16 ans, usage légal uniquement.",
            doc_terms_h4: '4. Téléphone comme identifiant', doc_terms_p4: "Votre numéro est votre identifiant unique et ne peut être modifié.",
            doc_terms_h5: '5. Conduite', doc_terms_p5: "Respectez les membres, pas de désinformation, pas d'usage du logo sans autorisation.",
            doc_terms_h6: '6. Responsabilité', doc_terms_p6: "RMN n'est pas responsable des dommages liés à l'utilisation du site.",
            doc_terms_h7: '7. Modifications', doc_terms_p7: "Nous pouvons modifier ces conditions. Les changements seront publiés.",
            doc_terms_h8: '8. Contact', doc_terms_p8: 'Email: info@fatraselo.net · WhatsApp: +509 4733 4565',
            doc_privacy_title: 'Politique de Confidentialité', doc_privacy_meta: 'Avril 2026 · Rezo Mapou Nasyonal',
            doc_privacy_h1: '1. Données collectées', doc_privacy_p1: 'Nom, email, téléphone, département, commune.',
            doc_privacy_h2: '2. Utilisation', doc_privacy_p2: 'Vous contacter sur les activités du réseau.',
            doc_privacy_h3: '3. Protection', doc_privacy_p3: "Google Sheets sécurisé. Seule l'équipe fondatrice a accès.",
            doc_privacy_h4: '4. Conservation', doc_privacy_p4: "Tant que le réseau est actif. Écrivez à info@fatraselo.net pour supprimer.",
            doc_privacy_h5: '5. Vos droits', doc_privacy_p5: 'Demandez copie, correction ou suppression à tout moment.',
            doc_privacy_h6: '6. Cookies', doc_privacy_p6: "Ce site n'utilise pas de cookies de suivi.",
            doc_privacy_h7: '7. Contact', doc_privacy_p7: 'Email: info@fatraselo.net · WhatsApp: +509 4733 4565',
            doc_copyright_title: "Droits d'Auteur", doc_copyright_meta: '© 2026 Rezo Mapou Nasyonal',
            doc_copyright_h1: '1. Propriété', doc_copyright_p1: 'Tout le contenu est la propriété exclusive de RMN.',
            doc_copyright_h2: '2. Marques', doc_copyright_p2: 'Les logos sont des marques enregistrées. Usage sans autorisation interdit.',
            doc_copyright_h3: '3. Interdictions', doc_copyright_p3: 'Pas de copie ou usage des logos sans autorisation écrite.',
            doc_copyright_h4: '4. Autorisé', doc_copyright_p4: 'Partage des liens avec attribution claire.',
            doc_copyright_h5: '5. Contenu utilisateur', doc_copyright_p5: 'En soumettant du contenu, vous accordez une licence à RMN.',
            doc_copyright_h6: '6. Contact', doc_copyright_p6: 'Email: info@fatraselo.net'
        },
        en: {
            lang_ht: 'Kreyol', lang_fr: 'French', lang_en: 'English',
            nav_home: 'Home', nav_about: 'Philosophy', nav_program: 'Program', nav_register: 'Register', nav_contact: 'Contact',
            footer_copyright: 'Copyright', footer_privacy: 'Privacy Policy',
            footer_terms: 'Terms of Use', footer_meta: '© 2026 Rezo Mapou Nasyonal',
            tab_filozofi: 'Philosophy', tab_program: 'Program',
            hero_tag: 'National Merchant Network - Haiti 2026',
            hero_h1a: 'You are', hero_h1b: 'Rezo Mapou.', hero_h1c: 'Come grow.',
            hero_lead: 'A national network supporting merchants and entrepreneurs across Haiti.',
            hero_cta1: 'Register Now - Free', hero_cta2: 'How It Works',
            map_eye: 'Our Symbol', map_title: 'Why Mapou?',
            map_p1: 'The Mapou tree is the most resilient tree in Haiti. It builds deep roots before rising.',
            map_p2: 'This is the same logic we use for this network. Together we form an unbreakable network.',
            map_dis_title: 'One thing important to state clearly:',
            map_dis1: 'Rezo Mapou has no religious affiliation of any kind.',
            map_dis2: 'Rezo Mapou has no political affiliation of any kind.',
            map_dis3: 'Everyone has a place in Rezo Mapou. One condition: wanting Haiti to move forward.',
            prog_eye: 'Map Sipote Lakay Program', prog_title: 'The steps, clearly.',
            ven_call: 'You hold up the economy. Join Rezo Mapou and access real benefits.',
            st1t: 'Register - Free', st1d: 'Registration open from today. Free.',
            st2t: 'A Coach Chooses You', st2d: 'Coaches browse profiles and choose who to support.',
            st3t: 'Receive Monthly Support', st3d: 'Each month you receive support from your Coach.',
            c1t: 'Post on Rezo Mapou', c1d: 'Share a post on the Rezo Mapou page.',
            c2t: 'Community Activity', c2d: 'Participate in at least one community activity.',
            c3t: 'Monthly Report', c3d: 'Complete the monthly network report.',
                        reg_title: 'Become a Rasin Mapou',
            reg_subtitle: 'Free. One minute. Register now.',
            f_sect_identity: 'Identity',
            f_firstname: 'First name', f_lastname: 'Last name',
            reg_gender: 'Gender', gender_f: 'Female', gender_m: 'Male', gender_x: 'Other',
            f_lang: 'Preferred language',
            f_email: 'Email', f_phone: 'Phone',
            f_sect_location: 'Location',
            f_country: 'Country', f_dept: 'Department', f_commune: 'Commune',
            f_city: 'City', f_state: 'State / Province',
            f_terms_consent: 'I accept the Terms and Privacy Policy of Rezo Mapou.',
            f_submit: 'Register now', f_submitting: 'Submitting...',
            f_success: 'Registration successful! We will contact you soon.',
            f_error: 'An error occurred. Please try again.',
            f_email_exists: 'This email is already registered.',
            f_phone_exists: 'This number is already registered.',
            f_email_ok: 'Email available.', f_phone_ok: 'Number available.',
            f_checking: 'Checking...',
            f_sect_payment: 'Payment (optional)',
            f_payment_hint: 'Account number to receive payments',
            pay_moncash: 'MonCash', pay_natcash: 'NatCash', pay_none: 'No account',
            f_sect_social: 'Social Networks (optional)'
            f_website: 'Website', f_success_title: 'Thank you — you are in the network!', f_whatsapp_exists: 'This WhatsApp is already registered.', f_whatsapp_ok: 'WhatsApp available.',,
            doc_terms_title: 'Terms of Use', doc_terms_meta: 'April 2026 · Rezo Mapou Nasyonal',
            doc_terms_h1: '1. Acceptance', doc_terms_p1: 'By using the site or registering as a member, you accept these terms.',
            doc_terms_h2: '2. Purpose', doc_terms_p2: 'A Haitian civil network. Apolitical and non-religious.',
            doc_terms_h3: '3. Registration', doc_terms_p3: 'Accurate information, over 16, legal use only.',
            doc_terms_h4: '4. Phone as Identifier', doc_terms_p4: 'Your phone number is your unique identifier and cannot be changed by you.',
            doc_terms_h5: '5. Conduct', doc_terms_p5: 'Respect members, no misinformation, no use of RMN logo without permission.',
            doc_terms_h6: '6. Liability', doc_terms_p6: 'RMN is not liable for damages from use of this site.',
            doc_terms_h7: '7. Changes', doc_terms_p7: 'We may modify these terms. Changes will be published on the site.',
            doc_terms_h8: '8. Contact', doc_terms_p8: 'Email: info@fatraselo.net · WhatsApp: +509 4733 4565',
            doc_privacy_title: 'Privacy Policy', doc_privacy_meta: 'April 2026 · Rezo Mapou Nasyonal',
            doc_privacy_h1: '1. Data collected', doc_privacy_p1: 'Name, email, phone, department, commune.',
            doc_privacy_h2: '2. Purpose', doc_privacy_p2: 'Contact you about network activities.',
            doc_privacy_h3: '3. Protection', doc_privacy_p3: 'Secured Google Sheets. Only founding team has access.',
            doc_privacy_h4: '4. Retention', doc_privacy_p4: 'While network is active. Email info@fatraselo.net to delete.',
            doc_privacy_h5: '5. Your rights', doc_privacy_p5: 'Request copy, correction or deletion at any time.',
            doc_privacy_h6: '6. Cookies', doc_privacy_p6: 'This site does not use tracking cookies.',
            doc_privacy_h7: '7. Contact', doc_privacy_p7: 'Email: info@fatraselo.net · WhatsApp: +509 4733 4565',
            doc_copyright_title: 'Copyright', doc_copyright_meta: '© 2026 Rezo Mapou Nasyonal',
            doc_copyright_h1: '1. Ownership', doc_copyright_p1: 'All content is the exclusive property of RMN.',
            doc_copyright_h2: '2. Trademarks', doc_copyright_p2: 'Logos are registered trademarks. Unauthorized use prohibited.',
            doc_copyright_h3: '3. Restrictions', doc_copyright_p3: 'No copying or use of logos without written permission.',
            doc_copyright_h4: '4. Permitted', doc_copyright_p4: 'Share site links with clear attribution.',
            doc_copyright_h5: '5. User content', doc_copyright_p5: 'By submitting content, you grant RMN a license to use it.',
            doc_copyright_h6: '6. Contact', doc_copyright_p6: 'Email: info@fatraselo.net'
        }
    },
    async init() {
        console.log("Initializing Language Service...");
        const stored = localStorage.getItem('rmn_lang');
        if (stored && this.dictionary[stored]) this.currentLang = stored;
        return true;
    },
    get(key) {
        const lang = this.dictionary[this.currentLang];
        return (lang && lang[key]) || key;
    },
    setLang(langCode) {
        if (this.dictionary[langCode]) {
            this.currentLang = langCode;
            localStorage.setItem('rmn_lang', langCode);
        }
    }
};
window.LangService = LangService;
